# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='tipo',
            field=models.CharField(choices=[('Python', 'python'), ('Linux', 'linux'), ('Javascript', 'javascript'), ('PHP', 'php'), ('Java', 'java'), ('Jquery', 'jquery'), ('Django', 'django')], default='Python', max_length=9, verbose_name='Tipo'),
        ),
    ]
